In [163]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session
import matplotlib.pyplot as plt
import seaborn as sns

/kaggle/input/books-dataset/books_data/ratings.csv
/kaggle/input/books-dataset/books_data/users.csv
/kaggle/input/books-dataset/books_data/books.csv

# data preprocessing

In [164]:
#importing data and ignoring the errors 
books_df = pd.read_csv("/kaggle/input/books-dataset/books_data/books.csv", sep=';', encoding='latin-1', on_bad_lines='skip')
ratings_df = pd.read_csv("/kaggle/input/books-dataset/books_data/ratings.csv", sep=';', encoding='latin-1', on_bad_lines='skip')
users_df = pd.read_csv("/kaggle/input/books-dataset/books_data/users.csv", sep=';', encoding='latin-1', on_bad_lines='skip')

/tmp/ipykernel_33/1903489317.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_df = pd.read_csv("/kaggle/input/books-dataset/books_data/books.csv", sep=';', encoding='latin-1', on_bad_lines='skip')

In [165]:
books_df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [166]:
books_df.tail()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [167]:
books_df.shape

(271360, 8)

In [168]:
books_df.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

we will keep only the important columns

In [169]:
books_df=books_df[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]

In [170]:
#rename the columns 
books_df.rename(columns={
    "Book-Title":"title",
    "Book-Author":"author",
    "Year-Of-Publication":"year",
    "Publisher":"publisher"},inplace=True)

In [171]:
books_df.head()

,ISBN,title,author,year,publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [172]:
users_df.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [173]:
#rename 
users_df.rename(columns={
    "User-ID":"user_id",
    },inplace=True)

In [174]:
users_df.shape

(278858, 3)

In [175]:
ratings_df.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [176]:
ratings_df.shape

(1149780, 3)

In [177]:
#rename 
ratings_df.rename(columns={
    "User-ID":"user_id",
    "Book-Rating":"rating"},inplace=True)

In [178]:
#users rating counts
ratings_df['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [179]:
#filtering users who read >150
x=ratings_df['user_id'].value_counts()>150
print(x[x].shape)

(1223,)

In [180]:
ratings_df=ratings_df[ratings_df['user_id'].isin(x[x].index)]

In [181]:
ratings_df.head()

      user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [182]:
ratings_df.shape

(582644, 3)

In [183]:
books_join_rate=ratings_df.merge(books_df,on="ISBN")
books_join_rate.head()

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books

In [184]:
#counting how many times a book was rated 
rating_count=books_join_rate.groupby('title')['rating'].count().reset_index()

In [185]:
rating_count.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       3
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [186]:
#filtering books with over 50 ratings
rating_count.rename(columns={'rating':'rate_count'},inplace=True)

In [187]:
rating_count.head()

                                               title  rate_count
0   A Light in the Storm: The Civil War Diary of ...           3
1                              Always Have Popsicles           1
2               Apple Magic (The Collector's series)           1
3   Beyond IBM: Leadership Marketing and Finance ...           1
4   Clifford Visita El Hospital (Clifford El Gran...           1

In [188]:
rating_count=books_join_rate.merge(rating_count,on='title')

In [189]:
#we have the number of rating For each book
rating_count.head()

,user_id,ISBN,rating,title,author,year,publisher,rate_count
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,88
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,15

In [190]:
#filtering boooks with more 50 ratings
rating_count=rating_count[rating_count['rate_count']>=50]
rating_count.shape

(77580, 8)

In [191]:
rating_count.drop_duplicates(['user_id','title'],inplace=True)

In [192]:
rating_count.shape

(75365, 8)

KNN

#  Model Training: KNN algorithm

1. Creating a pivot table to show user ratings for each book.
Each row represents a book title, each column represents a user ID,
and the values indicate the ratings given by users (scaled from 0 to 1).
2. clustering: We're going to find users who gave the same ratings to the same books. Then, we'll focus on recommending books they rated because they likely have similar interests.

In [193]:
books_pivot=rating_count.pivot_table(columns='user_id',index='title',values='rating')

In [194]:
books_pivot.head()

user_id,254,1733,1903,2033,2110,2276,2766,2891,2977,3363,...,274308,274808,275970,276018,276680,277427,277478,277639,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
books_pivot.shape

(884, 1206)

In [196]:
books_pivot.fillna(0,inplace=True)

In [197]:
books_pivot.head(2)

user_id,254,1733,1903,2033,2110,2276,2766,2891,2977,3363,...,274308,274808,275970,276018,276680,277427,277478,277639,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [198]:
# Importing the csr_matrix function from the scipy.sparse module.
# We'll use this function to create Compressed Sparse Row (CSR) matrices, 
# which are optimized for datasets with many zero values.
from scipy.sparse import csr_matrix

In [199]:
book_sparse=csr_matrix(books_pivot)

In [200]:
book_sparse

<884x1206 sparse matrix of type '<class 'numpy.float64'>'
	with 19598 stored elements in Compressed Sparse Row format>

In [201]:
#clustering
#distance calculation
from sklearn.neighbors import NearestNeighbors

In [202]:
model=NearestNeighbors(algorithm='brute')

In [203]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [204]:
# Finding the nearest neighbors for a specific book and printing the suggestions.
distance,suggestion=model.kneighbors(books_pivot.iloc[254,:].values.reshape(1,-1),n_neighbors=5)

In [205]:
distance

array([[ 0.        , 34.45286635, 34.71310992, 35.28455753, 35.62302626]])

In [206]:
suggestion

array([[254, 153, 384, 665, 132]])

In [207]:
for i in range(len(suggestion)):
    print(books_pivot.index[suggestion[i]]) #index for title

Index(['From the Corner of His Eye', 'Critical Judgment', 'Malice',
       'The Funhouse', 'Chromosome 6'],
      dtype='object', name='title')

In [208]:
books_name=books_pivot.index

In [209]:
import pickle
pickle.dump(model,open('Recc/model.pk1','wb'))
pickle.dump(books_name,open('Recc/books_name.pk1','wb'))
pickle.dump(rating_count_1,open('Recc/rating_count_1.pk1','wb'))
pickle.dump(books_pivot,open('Recc/books_pivot.pk1','wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'Recc/model.pk1'

In [ ]:
def recommend_book(book_name):
    book_id = np.where(books_pivot.index == book_name)[0]
    if len(book_id) == 0:
        print("Book not found.")
        return
    book_id = book_id[0]
    distance, suggestion = model.kneighbors(books_pivot.iloc[book_id, :].values.reshape(1, -1), n_neighbors=5)
    recommended_books = []
    for i in range(len(suggestion)):
        recommended_books.extend(books_pivot.index[suggestion[i]])
    return recommended_books

In [ ]:
books_pivot.index

In [210]:
book_name='A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash'
recommend_book(book_name)

['A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
 'Ground Zero and Beyond',
 'Four Blondes',
 'Personal Injuries',
 'Malice']

###